In [ ]:
numpy is python library ,was created in 2005 by Travis Oliphant. Numpy i used for working with arrays .
Numpy is short for "Numerical Python" 50x faster than array

In [ ]:
#importing numpy library
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


#different way to create numpy array


In [ ]:
#to create an array , we can pass a list ,tuple or
#other array like object

In [ ]:
#create 2d array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
#to see the dimension
print(arr3.ndim)

2


In [ ]:
#create 3d Array
arr4 = np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]
    ]])

print(arr4)
print(arr4.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [ ]:
#Numpy Array indexing
arr5=np.array([1,2,3,4,5])
print(arr5[2])

3


In [ ]:
print (arr5[0:3])
#using negative index
print(arr5[-2:-1])

[1 2 3]
[4]


In [ ]:
#get 3rd and 4th value and add them
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
#Access the element on the first row,second coulmn
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (arr)
print('2nd element on 1st row ',arr[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row  2


In [ ]:
#Acess the element on the 2nd row,5th column
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("5th element on 2nd row ",arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row  10


In [ ]:
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("last element from 2nd dim ",arr[1,-1])

last element from 2nd dim  10


In [ ]:
arr=np.array([10,20,30,40,50,60,75])
print(arr[1:5])
#slice elements from index 4 to the end of the array
print(arr[4:])
#slice element from 0 to index
print(arr[:4])
print(arr[-3:-1])

[20 30 40 50]
[50 60 75]
[10 20 30 40]
[50 60]


In [ ]:
arr=np.array([10,20,30,40,50,60,75])
print(arr[1:5:2])

print(arr[::4])

[20 40]
[10 50]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])

[7 8 9]
[3 8]


Data types in numpy

In [ ]:
#Numpy has some extra datatypes,and refer to data types with one character , like i for integers ,u for unsigned integers etc.

#i-integer etc


In [ ]:
#creating array with a defined data type
#create an array with data type string

arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr=np.array([1.1,1.2,1.3])
newarr=arr.astype('i')
print (newarr)
print(newarr.dtype)

[1 1 1]
int32


In [ ]:
#Numpy array copy vs view
# the main difference between a copy and a view of an array is that the copy is a new array , and a view is just a view of the original array.

In [ ]:
#Make a copy , change the original array, and display both arrays:

arr=np.array([1,2,3,4,5])
x=arr.copy();
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#view
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Numpy array shape
#the shape of an array is the number of elements in each array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#numpy array reshaping '
#reshaping means changing the shape of an array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Flattening the array
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
#numpy array iterating
#going through elements one by one
