1. Array Creation & Properties

In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.dtype)
print(arr.size)
print(arr.shape)

int64
5
(5,)


In [5]:
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
zeros=np.zeros((3,3))
print (zeros)
print()

ones=np.ones((3,3))
print(ones)
print()

identity=np.eye(3)
print(identity)
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [13]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [15]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


2.Array Arithmetic

In [16]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

square = arr ** 2
cube = arr ** 3

print("Square:", square)
print("Cube:", cube)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


In [18]:
import numpy as np

arr = np.array([100, 200, 300, 400])

new_arr = arr * 1.15

print(new_arr)

[115. 230. 345. 460.]


In [19]:
import numpy as np

a = np.array([10, 25, 30, 15])
b = np.array([20, 15, 35, 10])

maximum = np.maximum(a, b)
minimum = np.minimum(a, b)

print("Maximum:", maximum)
print("Minimum:", minimum)

Maximum: [20 25 35 15]
Minimum: [10 15 30 10]


3. Indexing & Slicing

In [20]:
import numpy as np

arr = np.arange(0, 21)

print("Array:", arr)

print("First five:", arr[:5])

print("Last five:", arr[-5:])

print("Index 5 to 15:", arr[5:16])

print("Every second element:", arr[::2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr[:5] = 100

print(arr)

[100 100 100 100 100   6   7   8   9  10]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Slice / View
view = arr[1:4]
view[0] = 100

print("Original after changing view:", arr)

# Copy
copy = arr[1:4].copy()
copy[0] = 200

print("Original after changing copy:", arr)
print("Copy:", copy)

Original after changing view: [  1 100   3   4   5]
Original after changing copy: [  1 100   3   4   5]
Copy: [200   3   4]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reverse = arr[::-1]

print(reverse)

[5 4 3 2 1]


4. 2-D Array Indexing & Slicing

In [24]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", arr[1, :])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [25]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

sub_matrix = arr[0:2, 1:3]

print(sub_matrix)

[[20 30]
 [50 60]]


In [26]:
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(arr)

print("First row:", arr[0, :])

print("Last column:", arr[:, -1])

print("Middle element:", arr[2, 2])

print("Top-left 3 × 3 matrix:")
print(arr[:3, :3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3 × 3 matrix:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


5. Reshaping & Transpose

In [27]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
arr=np.arange(1,11).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

transpose = arr.T

print("Original:")
print(arr)

print("Transpose:")
print(transpose)

Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [31]:
import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)

print("Original:")
print(arr)

print("Using transpose():")
print(arr.transpose())

print("Using swapaxes():")
print(arr.swapaxes(0, 1))

Original:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Using transpose():
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
Using swapaxes():
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
